logging:
  level:
    org.springframework: WARN
    net.check321: INFO
  pattern:
    console: "[%thread] %d{yyyy-MM-dd HH:mm:ss:SSS} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"